hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_a946ea8b949cf70?&serverTimezone=UTC&useSSL=false
hibernate.connection.username=b7d40f13f81591
hibernate.connection.password=1b8278fd
hibernate.dialecthibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=false
hibernate.current_session_context_class=thread
hibernate.hbm2ddl.auto=none