hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_230d88d6f469b29?&serverTimezone=UTC&useSSL=false
hibernate.connection.username=b2b101a10236d7
hibernate.connection.password=63d01327
hibernate.dialecthibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=false
hibernate.current_session_context_class=thread
hibernate.hbm2ddl.auto=none